[project]
name = 'carbon'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.CarbonCreditEvents]
path = 'contracts/CarbonCreditEvents.clar'
clarity_version = 3
epoch = '3.2'

[contracts.CarbonCredits]
path = 'contracts/CarbonCredits.clar'
clarity_version = 3
epoch = '3.2'

[contracts.CarbonListing]
path = 'contracts/CarbonListing.clar'
clarity_version = 3
epoch = '3.2'

[contracts.CarbonMarketplace]
path = 'contracts/CarbonMarketplace.clar'
clarity_version = 3
epoch = '3.2'

[contracts.CarbonRetirement]
path = 'contracts/CarbonRetirement.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
